name: Build and Analyze

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Create .env.local files
        run: |
          # Your existing .env.local file creation steps here

      - name: Build
        run: pnpm build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: apps/app/.next # Adjust this path to your Next.js app location

  analyze:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: apps/app/.next # Adjust this path to your Next.js app location

      - name: Install nextjs-bundle-analysis
        run: pnpm add -D nextjs-bundle-analysis

      - name: Analyze bundle
        run: pnpm dlx cross-env ANALYZE=true next build
        working-directory: apps/app # Adjust this to your Next.js app location

      - name: Upload bundle
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: apps/app/.next/analyze/__bundle_analysis.json # Adjust this path

      - name: Download base branch bundle stats
        uses: dawidd6/action-download-artifact@v2
        if: github.event_name == 'pull_request'
        with:
          workflow: build-and-analyze.yml
          branch: ${{ github.event.pull_request.base.ref }}
          path: apps/app/.next/analyze/base # Adjust this path

      - name: Compare with base branch bundle
        if: github.event_name == 'pull_request'
        run: pnpm dlx nextjs-bundle-analysis compare
        working-directory: apps/app # Adjust this path

      - name: Get comment body
        id: get-comment-body
        if: github.event_name == 'pull_request'
        run: |
          body=$(cat .next/analyze/__bundle_analysis_comment.txt)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "body=$body" >> $GITHUB_OUTPUT
        working-directory: apps/app # Adjust this path

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        if: github.event_name == 'pull_request'
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Bundle Size

      - name: Create Comment
        uses: peter-evans/create-or-update-comment@v2
        if: github.event_name == 'pull_request'
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.get-comment-body.outputs.body }}
          edit-mode: replace
          comment-id: ${{ steps.fc.outputs.comment-id }}